title: TABConf 8
description: >-
  TABConf is a technical Bitcoin conference — protocol and application
  developers collaborating, debating, and building in Atlanta.
url: "https://8.tabconf.com"
baseurl: ""
permalink: pretty
markdown: kramdown
